import{a as h,S,i as a}from"./assets/vendor-frHSA4Lh.js";(function(){const r=document.createElement("link").relList;if(r&&r.supports&&r.supports("modulepreload"))return;for(const t of document.querySelectorAll('link[rel="modulepreload"]'))i(t);new MutationObserver(t=>{for(const s of t)if(s.type==="childList")for(const d of s.addedNodes)d.tagName==="LINK"&&d.rel==="modulepreload"&&i(d)}).observe(document,{childList:!0,subtree:!0});function o(t){const s={};return t.integrity&&(s.integrity=t.integrity),t.referrerPolicy&&(s.referrerPolicy=t.referrerPolicy),t.crossOrigin==="use-credentials"?s.credentials="include":t.crossOrigin==="anonymous"?s.credentials="omit":s.credentials="same-origin",s}function i(t){if(t.ep)return;t.ep=!0;const s=o(t);fetch(t.href,s)}})();h.defaults.baseURL="https://pixabay.com/api/";async function g(e,r){try{return(await h.get("",{params:{key:"16912349-7bb97ffb55ee20e1561898d9f",q:e,image_type:"photo",orientation:"horizontal",safesearch:!0,page:r,per_page:15}})).data}catch(o){throw console.error("Помилка при отриманні зображень:",o),o.response?(console.error("Статус відповіді:",o.response.status),console.error("Дані відповіді:",o.response.data)):o.request?console.error("Запит був зроблений, але відповіді не було:",o.request):console.error("Помилка налаштування запиту:",o.message),o}}const m=document.querySelector(".gallery"),y=document.querySelector(".loader"),b=document.querySelector(".load-more-btn"),C=new S(".gallery a",{captionsData:"alt",captionDelay:250});function I(){m.innerHTML=""}function P(e){return`
    <li class="gallery-item">
      <a class="gallery-link" href="${e.largeImageURL}">
        <img
          class="gallery-image"
          src="${e.webformatURL}"
          alt="${e.tags}"
        />
      </a>
      <div class="info">
        <p class="info-item"><b>Likes</b> ${e.likes}</p>
        <p class="info-item"><b>Views</b> ${e.views}</p>
        <p class="info-item"><b>Comments</b> ${e.comments}</p>
        <p class="info-item"><b>Downloads</b> ${e.downloads}</p>
      </div>
    </li>
  `}function L(e){if(!e||e.length===0)return;const r=e.map(t=>P(t)).join(""),o=document.createElement("div");o.innerHTML=r;const i=document.createDocumentFragment();for(;o.firstChild;)i.appendChild(o.firstChild);m.appendChild(i),C.refresh()}function v(){y.classList.add("is-visible")}function p(){y.classList.remove("is-visible")}function w(){b.classList.add("is-visible")}function c(){b.classList.remove("is-visible")}const u=document.querySelector(".form"),R=u.elements.query,E=document.querySelector(".load-more-btn");let l="",n=1;const q=15;let f=0;p();c();u.addEventListener("submit",async e=>{if(e.preventDefault(),l=R.value.trim(),n=1,I(),c(),!l){a.error({title:"Error",message:"Search field cannot be empty!",position:"topRight"});return}v();try{const r=await g(l,n);f=r.totalHits,r.hits.length===0?a.info({title:"Info",message:"Sorry, there are no images matching your search query. Please try again!",position:"topRight"}):(L(r.hits),f>q?w():a.info({title:"Info",message:"We're sorry, but you've reached the end of search results.",position:"topRight"}))}catch(r){a.error({title:"Error",message:"Failed to fetch images. Please try again later.",position:"topRight"}),console.error("Error in search form submit:",r)}finally{p(),u.reset()}});E.addEventListener("click",async()=>{n+=1,v(),c();try{const e=await g(l,n);L(e.hits);const r=m.querySelector(".gallery-item");if(r){const i=r.getBoundingClientRect().height;window.scrollBy({top:i*2,behavior:"smooth"})}n*q>=f?(c(),a.info({title:"Info",message:"We're sorry, but you've reached the end of search results.",position:"topRight"})):w()}catch(e){a.error({title:"Error",message:"Failed to load more images. Please try again later.",position:"topRight"}),console.error("Error loading more images:",e)}finally{p()}});
//# sourceMappingURL=index.js.map
